---
- name: Check root filesystem usage
  hosts: all
  become: true
  vars:
    path: "/"

  tasks:
    - name: set Filesystem usage fact
      ansible.builtin.set_fact:
        root_path: "{{( ansible_facts.mounts | selectattr('mount', 'in', path))[-1] }}"
  
    - name: delete files if root filesystem is less than 20% available
      when: (root_path.size_available/root_path.size_total*100) | int < 20
      block:
       - name: Analyzing the file to delete...
         ansible.builtin.find:
           paths: /tmp
           patterns: "*.file"
           age: 5
           age_stamp: atime
         register: files_to_delete

       - name: Displaying the result...
         ansible.builtin.debug:
           var: files_to_delete.files

       - name: Deleting the files...
         ansible.builtin.file:
           path: "{{ item.path }}"
           state: absent
         with_items: "{{ files_to_delete.files }}"




