---
- name: Check root filesystem usage
  hosts: all
  become: true
  vars:
    filesystem: "/"

  tasks:
    - name: Get filesystem usage
      ansible.builtin.shell: df -h {{ filesystem }} | awk 'NR==2 {print $5}' | sed 's/%//'
      register: filesystem_usage
      changed_when: false

    - name: output size available
      ansible.builtin.debug:
        msg: size_available = 
    - name: Set fact for filesystem usage
      ansible.builtin.set_fact:
        root_fs_usage: "{{ filesystem_usage.stdout | int }}"

    - name: delete files if root filesystem is more than 80% full
      when: ansible_mounts['/']['size_available'] / ansible_mounts['/']['size_total'] < "20"
      block:
       - name: Categorize filesystem usage
         ansible.builtin.debug:
           msg: >
             Root filesystem usage is ({{ root_fs_usage }}%) utilized

       - name: Analyzing the directories to delete...
         ansible.builtin.find:
           paths: /tmp
           patterns: "*.file"
           age: 5
           age_stamp: atime
         register: files_to_delete

       - name: Displaying the result...
         ansible.builtin.debug:
           var: files_to_delete.files

       - name: Deleting the files...
         ansible.builtin.file:
           path: "{{ item.path }}"
           state: absent
         with_items: "{{ files_to_delete.files }}"
