---
- name: Check root filesystem usage
  hosts: all
  become: true
  vars:
    filesystem: "/"

  tasks:
    - name: Get filesystem usage
      ansible.builtin.shell: df -h {{ filesystem }} | awk 'NR==2 {print $5}' | sed 's/%//'
      register: filesystem_usage
      changed_when: false

    - name: Set fact for filesystem usage
      ansible.builtin.set_fact:
        root_fs_usage: "{{ filesystem_usage.stdout | int }}"

    - name: Categorize filesystem usage
      ansible.builtin.debug:
        msg: >
          Root filesystem usage is ({{ root_fs_usage }}%) utilized
      when: root_fs_usage > "80"

#    - name: Recursively find /var/tmp files with last access time greater than 3600 seconds
#      ansible.builtin.find:
#        paths: /tmp
#        age: 5
#        age_stamp: atime
#        recurse: yes
#      register: files_to_delete

    - name: Analyzing the directories to delete...
      ansible.builtin.find:
        paths: /tmp
        patterns: "*.file"
        use_regex: true
      register: files_to_delete

    - name: Displaying the result...
      ansible.builtin.debug:
        var: files_to_delete

    - name: Deleting the files...
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

#    - name: remove /tmp/*.file
#      ansible.builtin.file:
#        path: {{ item }}
#        state: absent
#      with_fileglob: "/tmp/*.file"
#      when: root_fs_usage > "80"