---
- name: Fill up a filesystem
  hosts: all
  become: true

  tasks:
  - name: Create a file of 1G filled with null bytes
    ansible.builtin.filesize:
      path: /tmp/large.file
      size: 4G
      source: /dev/zero