---
- name: Fill up a filesystem
  hosts: all
  become: true

  tasks:
  - name: Create a file of 5G filled with zeros
    community.general.filesize:
      path: /tmp/large.file
      size: 5G
      source: /dev/zero