---
- name: install postgresql on vm2.home.io
  hosts: all
  become: true
  tasks:
    - name: install postgresql
      become: true
      ansible.builtin.package:
        name:
          - postgresql
        state: present

    

