---
- name: Configure nbde client to unlock the disk for Fedora servers
  hosts: all
  become: yes
  vars:
    nbde_client_bindings:
      - device: "{{ device_var }}"
        encryption_password: "{{ _encryption_password_ }}"
        servers:
          - "{{ tang_server_var }}"
  roles:
    - redhat.rhel_system_roles.nbde_client