---
- name: Configure nbde client to unlock the disk for Fedora servers
  hosts: all
#  become: true
  vars:
    nbde_client_bindings:
      - device: "{{ device_var }}"
        encryption_password: "{{ _encryption_password_ }}"
        servers:
          - "{{ tang_server_var }}"
  tasks:
    - name: Verify become
      ansible.builtin.shell: whoami
  
    - name: include role
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.nbde_client
