---
- name: Set up automatic unlock
  hosts: all
  become: true
  vars:
    nbde_client_bindings:
      - device: "{{ device_var }}"
        encryption_password: "{{ encryption_pw_var }}"
        servers:
          - "{{ tang_server_var | default('http://fedora.home.io') }}"
  roles:
    - redhat.rhel_system_roles.nbde_client
