---
- name: Check root filesystem usage
  hosts: all
  tasks:
#     - name: Block - Get Endpoint ID
#       block:
    - name: Get Endpoint ID
    # https://docs.ansible.com/ansible/latest/collections/cisco/ise/endpoint_info_module.html#ansible-collections-cisco-ise-endpoint-info-module
      cisco.ise.endpoint_info:
        ise_hostname: "{{  CISCO_ISE_HOST  }}"
        ise_username: "{{  CISCO_ISE_USERNAME }}"
        ise_password: "{{  CISCO_ISE_PASSWORD }}"
        ise_verify: "{{ ise_verify }}"
        name: "{{  endpoint_name  }}"
      register: 
         - id_mac
      failed_when:
        - "'FAILED' in id_mac.stderr"
        - "'404' not in id_mac.stderr"