---
- name: Passwordless SUDO 
  hosts: all
  become: true
  tasks:
    - name: Passwordless sudo for wheel group
      ansible.builtin.copy:
        dest: /etc/sudoers.d/passwordless-wheel
        content: '%wheel	ALL=(ALL)	NOPASSWD: ALL'
