---
- name: Passwordless SUDO
  hosts: all
  become: true
  tasks:
    - name: Passwordless sudo for wheel group  #  noqa no-tabs
      ansible.builtin.copy:
        dest: /etc/sudoers.d/passwordless-wheel
        content: "%wheel	ALL=(ALL)	NOPASSWD: ALL" #  noqa no-tabs
        mode: "0622"
