---
- name: Reboot the AT&T Residential gateway by turning off and back on the outlet its plugged into
  hosts: all
  tasks:
    - name: Reboot AT&T RG
      ansible.builtin.expect:
        command: /usr/bin/telnet pdu2.home.io
        responses:
            "Password:":
                - "password" #Do I need to include the \r return command?
            "IPS>":
                - "/S" #Do I need to include the \r return command?
            "IPS>":
                - "/X" #Do I need to include the \r return command?
            "Sure? (Y/N):":
                - "Y" #Do I need to include the \r return command?