---
- name: Reboot the AT&T Residential gateway by turning off and back on the outlet its plugged into
  hosts: all
  tasks:
    - name: Reboot AT&T RG
      ansible.builtin.shell: logger "Rebooting AT&T Gateway"
      ansible.builtin.shell: /home/mike/reboot-rg