---
- name: start the httpd service
  hosts: all
  become: true
  tasks:
    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: started
        name: httpd
        