---
- name: STIG Playbook Test
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: RHEL 8 STIG Rule 230264 - Find Repo Files 
      ansible.builtin.find:
        paths: /etc/yum.repos.d
        recurse: true
        patterns: "*.repo"
      register: yum_repos
# Some repo files can have multiple repos. Need to get repo name from each file and set gpgcheck = 1, and add it if its not present
    - name: STIG Rule 230264 - Set gpgcheck value to 1 for each repo
      ansible.builtin.blockinfile:
        path: "{{ item.path }}"
        block: |
          gpgcheck=1
        insertafter: '^\[.*\]'
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR GPGCHECK"
      loop: "{{ yum_repos.files }}"
      check_mode: false
    - name: STIG Rule 230264 - Ensure gpgcheck=1 for existing entries
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^gpgcheck\s*=\s*0'
        replace: 'gpgcheck=1'
      loop: "{{ yum_repos.files }}"