---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 3002

  rules:
    - name: Delete files from /tmp if >= 80% utilized
      condition: event.payload.usage >= "80"
      action:
        run_job_template:
          name: Check and Delete Files
          organization: Default

    - name: Detected a failed login
      condition: event.payload.error == "ssh-failed"
      action:
        run_job_template:
          name: Failed Login Attempt
          organization: Default
          job_args:
            extra_vars:
              failed_ip: "{{ event.payload.ipaddress }}"

    - name: Detected a failed sudo
      condition: event.payload.error == "sudo-failed"
      action:
        run_job_template:
          name: Failed sudo Attempt
          organization: Default
          job_args:
            extra_vars:
              failed_ip: "{{ event.payload.log }}"

    - name: Detected a changed file
      condition: event.payload.error == "file-edited"
      action:
        run_job_template:
          name: Config File Change
          organization: Default
          job_args:
            extra_vars:
              failed_ip: "{{ event.payload.log }}"

