---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 3002

  rules:
    - name: Delete files from /tmp if >= 80% utilized
      condition: event.payload.usage >= "80"
      action:
        run_job_template:
          name: deletefiles
          organization: Default
